"""add relationship 2

Revision ID: 5c1c3c7ef547
Revises: fc73dfcd953c
Create Date: 2024-03-24 22:06:30.957765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c1c3c7ef547"
down_revision: Union[str, None] = "fc73dfcd953c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
