"""add relationship

Revision ID: fc73dfcd953c
Revises: e6b8dc8a4e4d
Create Date: 2024-03-24 21:46:34.427951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc73dfcd953c"
down_revision: Union[str, None] = "e6b8dc8a4e4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subprojects",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "projects", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "projects", "users", ["user_id"], ["id"])
    op.drop_column("projects", "main_project")
    op.add_column(
        "tasks", sa.Column("project_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "tasks", "projects", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "project_id")
    op.add_column(
        "projects",
        sa.Column(
            "main_project", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_column("projects", "user_id")
    op.drop_table("subprojects")
    # ### end Alembic commands ###
